language: php
php:
  - nightly
  - hhvm
  - 7.1
  - 7.0
  - 5.6
  - 5.5

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer require codeclimate/php-test-reporter:dev-master --dev
  - composer update --no-interaction --prefer-dist

script:
  - ./vendor/phpunit/phpunit/phpunit -v --coverage-clover build/logs/clover.xml

addons:
    code_climate:
        repo_token: 4e81c8917f95305095873565e2e20746ce034a77a4337f39612e572051ae6048